/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *nine;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *minus;
  GtkWidget *zero;
  GtkWidget *dot;
  GtkWidget *equal;
  GtkWidget *plus;
  GtkWidget *clear;
  GtkWidget *seven;
  GtkWidget *four;
  GtkWidget *one;
  GtkWidget *bksp;
  GtkWidget *ce;
  GtkWidget *eight;
  GtkWidget *pm;
  GtkWidget *two;
  GtkWidget *div;
  GtkWidget *three;
  GtkWidget *mul;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("my calculator"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 88, 24);
  gtk_widget_set_size_request (entry1, 392, 72);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 312, 224);
  gtk_widget_set_size_request (nine, 102, 40);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 168, 304);
  gtk_widget_set_size_request (five, 116, 40);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 312, 304);
  gtk_widget_set_size_request (six, 117, 40);

  minus = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (minus);
  gtk_fixed_put (GTK_FIXED (fixed1), minus, 448, 368);
  gtk_widget_set_size_request (minus, 117, 40);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 24, 448);
  gtk_widget_set_size_request (zero, 117, 40);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 168, 448);
  gtk_widget_set_size_request (dot, 117, 40);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 312, 448);
  gtk_widget_set_size_request (equal, 116, 40);

  plus = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (plus);
  gtk_fixed_put (GTK_FIXED (fixed1), plus, 456, 448);
  gtk_widget_set_size_request (plus, 115, 40);

  clear = gtk_button_new_with_mnemonic (_("clr"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 312, 160);
  gtk_widget_set_size_request (clear, 102, 40);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 16, 224);
  gtk_widget_set_size_request (seven, 101, 40);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 16, 304);
  gtk_widget_set_size_request (four, 101, 40);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 16, 368);
  gtk_widget_set_size_request (one, 117, 40);

  bksp = gtk_button_new_with_mnemonic (_("Bksp"));
  gtk_widget_show (bksp);
  gtk_fixed_put (GTK_FIXED (fixed1), bksp, 16, 160);
  gtk_widget_set_size_request (bksp, 102, 40);

  ce = gtk_button_new_with_mnemonic (_("ce\n"));
  gtk_widget_show (ce);
  gtk_fixed_put (GTK_FIXED (fixed1), ce, 168, 160);
  gtk_widget_set_size_request (ce, 101, 40);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 168, 224);
  gtk_widget_set_size_request (eight, 102, 40);

  pm = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (pm);
  gtk_fixed_put (GTK_FIXED (fixed1), pm, 448, 160);
  gtk_widget_set_size_request (pm, 102, 40);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 168, 368);
  gtk_widget_set_size_request (two, 117, 40);

  div = gtk_button_new_with_mnemonic (_("\303\267"));
  gtk_widget_show (div);
  gtk_fixed_put (GTK_FIXED (fixed1), div, 448, 224);
  gtk_widget_set_size_request (div, 102, 40);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 312, 368);
  gtk_widget_set_size_request (three, 116, 40);

  mul = gtk_button_new_with_mnemonic (_("\303\227"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed1), mul, 448, 304);
  gtk_widget_set_size_request (mul, 116, 40);

  g_signal_connect ((gpointer) window1, "destroy",
                    G_CALLBACK (on_window1_destroy),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) minus, "clicked",
                    G_CALLBACK (on_minus_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) plus, "clicked",
                    G_CALLBACK (on_plus_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) bksp, "clicked",
                    G_CALLBACK (on_bksp_clicked),
                    NULL);
  g_signal_connect ((gpointer) ce, "clicked",
                    G_CALLBACK (on_ce_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) pm, "clicked",
                    G_CALLBACK (on_pm_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) div, "clicked",
                    G_CALLBACK (on_div_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, minus, "minus");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, plus, "plus");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, bksp, "bksp");
  GLADE_HOOKUP_OBJECT (window1, ce, "ce");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, pm, "pm");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, div, "div");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, mul, "mul");

  return window1;
}

